## HW 1 ##

### Problem 2 ###

**Some definitions**

Let 

$$M\in\mathbb{R}^{n\times n}$$ be an arbitrary matrix.  

Let $$p(x)=a_0 + a_1 x + a_2 x^2 + \ldots + a_n x^n \in\mathbb{R}[x]$$ be an arbitrary polynomial of less or equal to $n$.

The above polynomial can be used to define a matrix function that takes matrices as input and outputs matrices as follows: 

$$p(M) = a_0 I + a_1 M + \ldots + a_n M^n,$$ 

that is, each monomial $x^k$ is substituted by the corresponding matrix power $M^k$.

We say that a polynomial $p(x)$ annihilates a matrix $M\in\mathbb{R}^{n\times n}$ iff $p(M)=\boldsymbol{0}$, where $\boldsymbol{0}$ is the zero matrix.

**Task**

The task is to write a function ```annihilate_poly``` that takes as input an arbitrary square numpy array $M$ and outputs a vector whose cofficients are the coefficients of a (non-trivial) polynomial that annihilates $M$.  One-trivial means that its is not the zero polynomial which maps every matrix to the zero matrix.

**Hint**

You can reduce the problem to finding a linear dependance relationship between the $n+1$ vectors 

$$\mathrm{vec}(I), \mathrm{vec}(M), \mathrm{vec}(M^2),\ldots,\mathrm{vec}(M^n)\in\mathrm{R}^{n^2}.$$



The operation $\mathrm{vec}$ turns a square matrix $M\in\mathbb{R}^{n\times n}$ into a vector $v\in\mathbb{R}^{n^2}$ by first listing the entries of the first row, then those of the second row etc.

Update: 

To solve this problem, you have to compute the null space of the matrix $A\in \mathbb{R}^{n^2\times (n+1)}$ whose columns are the vectors $\mathrm{vec}(M^k)$ for $k\in\{0,\ldots,n\}$.


(This is not needed: 

If you don't remeber how to compute the find a linear dependance relationship, check out this stackoverflow post: https://math.stackexchange.com/questions/2198960/finding-linear-dependence-relation

You can use https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html to solve the resulting matrix equation.)

**Task**

Write a function ```annihilate_min_deg_poly``` that computes a non-trivial polynomial that annihilates a given square matrix and has the smallest possible degree.  Recall that a polynomial $p(x)$ has degree $d$ if the coefficient $a_{d+1}=\ldots=a_n=0$.

################################################################################################# ################################################################################################# #################################################################################################

Solution

Import required libraries

In [0]:
import numpy as np
from scipy.linalg import null_space
np.set_printoptions(precision=8)

Define annihilate_poly function

In [0]:
def annihilate_poly(M):
    n = M.shape[1]
    I = np.eye(n, dtype=int)
    A =  I.flatten()
    A = np.reshape(A, (-1, 1))
    for x in range(1,n+1):
        temp = np.linalg.matrix_power(M,x)
        temp = np.transpose(temp.flatten())
        temp = np.reshape(temp, (-1, 1))
        A = np.concatenate((A,temp),axis=1)
        
    print("Matrix A=")    
    print(A)
    Coef = null_space(A)
    return Coef

define annihilate_min_def_poly function

In [0]:
def annihilate_min_def_poly(M):
    n = M.shape[1]
    I = np.eye(n, dtype=int)
    A =  I.flatten()
    A = np.reshape(A, (-1, 1))
    x=1
    while True:
        temp = np.linalg.matrix_power(M,x)
        temp = np.transpose(temp.flatten())
        temp = np.reshape(temp, (-1, 1))
        A = np.concatenate((A,temp),axis=1)
        Coef = null_space(A)
        if(Coef.size!=0):
            print("Min Degree is")
            print(x)
            break
        x=x+1 
#     print("Matrix A=")    
#     print(A)
    return Coef

Function to test the polynomial

In [0]:
def Polytest(M,Coef):
    n = M.shape[1]
    I = np.eye(n, dtype=int)
    Val = I*Coef[0]
    for x in range(1,Coef.shape[0]):
        Val = Val + np.linalg.matrix_power(M,x)*Coef[x]
           
    return Val

We created 3 sample matrixes M1, M2, and M3 with sizes n=2, 3, and 4

In [0]:
S = 2
M1 = np.random.randint(10,size=(S,S))
S = 3
M2 = np.random.randint(10,size=(S,S))
S = 4
M3 = np.random.randint(10,size=(S,S))

#################################################################################################

Test Cases On annihilate_poly

#################################################################################################

Test for Matrix M1

In [0]:
print("M1 Matrix is:")
print(M1)
Coef = annihilate_poly(M1)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M1,Coef)
print("P(M)=")
print(Out)

M1 Matrix is:
[[7 1]
 [9 4]]
Matrix A=
[[ 1  7 58]
 [ 0  1 11]
 [ 0  9 99]
 [ 1  4 25]]
Coefficients:
[[ 0.86452993]
 [-0.50051733]
 [ 0.04550158]]
P(M)=
[[2.22044605e-15 3.33066907e-16]
 [3.55271368e-15 1.11022302e-15]]


Test for Matrix M2

In [0]:
print("M2 Matrix is:")
print(M2)
Coef = annihilate_poly(M2)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M2,Coef)
print("P(M)=")
print(Out)

M2 Matrix is:
[[2 8 6]
 [3 3 6]
 [9 1 4]]
Matrix A=
[[   1    2   82 1058]
 [   0    8   46  878]
 [   0    6   84 1104]
 [   0    3   69  795]
 [   1    3   39  729]
 [   0    6   60  888]
 [   0    9   57 1035]
 [   0    1   79  769]
 [   1    4   76 1120]]
Coefficients:
[[ 0.96100343]
 [ 0.27322646]
 [ 0.04239721]
 [-0.0047108 ]]
P(M)=
[[ 3.81916720e-14 -6.21724894e-15 -9.76996262e-15]
 [-7.54951657e-15  4.17443857e-14 -7.10542736e-15]
 [-7.99360578e-15 -7.54951657e-15  3.81916720e-14]]


Test for Matrix M2

In [0]:
print("M3 Matrix is:")
print(M3)
Coef = annihilate_poly(M3)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M3,Coef)
print("P(M)=")
print(Out)

M3 Matrix is:
[[8 6 8 2]
 [4 7 3 9]
 [3 9 0 3]
 [7 3 8 8]]
Matrix A=
[[    1     8   126  2744 62270]
 [    0     6   168  3144 68814]
 [    0     8    98  2392 54888]
 [    0     2   110  2938 64464]
 [    0     4   132  3003 66017]
 [    1     7   127  3262 73723]
 [    0     3   125  2653 57794]
 [    0     9   152  2998 67307]
 [    0     3    81  2010 44589]
 [    0     9    90  2124 49437]
 [    1     0    75  1806 39132]
 [    0     3   111  2085 45234]
 [    0     7   148  3110 69177]
 [    0     3   159  3549 77178]
 [    0     8   129  2693 60695]
 [    1     8   129  3146 71408]]
Coefficients:
[[-0.56697307]
 [-0.81960392]
 [ 0.06942527]
 [-0.04435504]
 [ 0.00192848]]
P(M)=
[[-7.38964445e-13  1.59161573e-12  5.18696197e-12  1.13686838e-12]
 [ 1.63424829e-12 -6.53699317e-13  6.39488462e-13  4.32009983e-12]
 [ 1.69109171e-12  5.84066129e-12 -5.72697445e-12  3.55271368e-13]
 [ 3.24007488e-12  5.11590770e-13  4.19220214e-12 -1.98951966e-13]]


#################################################################################################

Test Cases On annihilate_min_def_poly

#################################################################################################

Test for Matrix M1

In [0]:
print("M1 Matrix is:")
print(M1)
Coef = annihilate_min_def_poly(M1)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M1,Coef)
print("P(M)=")
print(Out)

M1 Matrix is:
[[7 1]
 [9 4]]
Min Degree is
2
Coefficients:
[[ 0.86452993]
 [-0.50051733]
 [ 0.04550158]]
P(M)=
[[2.22044605e-15 3.33066907e-16]
 [3.55271368e-15 1.11022302e-15]]


Test for Matrix M2

In [0]:
print("M2 Matrix is:")
print(M2)
Coef = annihilate_min_def_poly(M2)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M2,Coef)
print("P(M)=")
print(Out)

M2 Matrix is:
[[2 8 6]
 [3 3 6]
 [9 1 4]]
Min Degree is
3
Coefficients:
[[ 0.96100343]
 [ 0.27322646]
 [ 0.04239721]
 [-0.0047108 ]]
P(M)=
[[ 3.81916720e-14 -6.21724894e-15 -9.76996262e-15]
 [-7.54951657e-15  4.17443857e-14 -7.10542736e-15]
 [-7.99360578e-15 -7.54951657e-15  3.81916720e-14]]


Test for Matrix M3

In [0]:
print("M3 Matrix is:")
print(M3)
Coef = annihilate_min_def_poly(M3)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M3,Coef)
print("P(M)=")
print(Out)

M3 Matrix is:
[[8 6 8 2]
 [4 7 3 9]
 [3 9 0 3]
 [7 3 8 8]]
Min Degree is
4
Coefficients:
[[-0.56697307]
 [-0.81960392]
 [ 0.06942527]
 [-0.04435504]
 [ 0.00192848]]
P(M)=
[[-7.38964445e-13  1.59161573e-12  5.18696197e-12  1.13686838e-12]
 [ 1.63424829e-12 -6.53699317e-13  6.39488462e-13  4.32009983e-12]
 [ 1.69109171e-12  5.84066129e-12 -5.72697445e-12  3.55271368e-13]
 [ 3.24007488e-12  5.11590770e-13  4.19220214e-12 -1.98951966e-13]]


#################################################################################################

For bigger matrices with size bigger than 7 annihilation needs polynomials of order 49 and is not very effective as for smaller matrices. As you can see in the following example the P(M) annihilates to numbers of order 1e-6 or 1e-7 while for matrices M of size 4 P(M) annihilated to numbers of order 1e-13

Test Case with M 7x7 Matrix.

In [0]:
S = 7
M6 = np.random.randint(10,size=(S,S))
print("M6 Matrix is:")
print(M6)
Coef = annihilate_min_def_poly(M6)
print("=============================================")
print("Coefficients:")
print(Coef)
print("=============================================")
Out = Polytest(M6,Coef)
print("P(M)=")
print(Out)

M6 Matrix is:
[[8 2 0 1 5 0 0]
 [0 3 4 9 9 7 0]
 [2 4 2 6 9 3 6]
 [9 5 2 4 4 5 8]
 [8 8 5 7 9 7 2]
 [5 5 9 0 2 0 8]
 [4 4 2 7 5 3 2]]
Min Degree is
7
Coefficients:
[[-9.48892245e-01]
 [-3.14738313e-01]
 [ 1.62112399e-02]
 [ 1.67236193e-02]
 [ 8.50425600e-04]
 [-3.01901087e-04]
 [-5.95297919e-05]
 [ 2.12606400e-06]]
P(M)=
[[-4.09583663e-07 -4.92937033e-08  1.11531335e-08  1.90084393e-10
  -1.53157089e-07  4.14529495e-08 -1.74486559e-08]
 [ 1.56398528e-07 -1.18156095e-07 -6.35409378e-08 -3.83886800e-07
  -3.56254532e-07 -2.38200300e-07  1.86491889e-07]
 [ 2.94876372e-08 -6.96509233e-08 -1.37717507e-07 -1.52429493e-07
  -3.12413249e-07 -2.54385668e-08 -2.30613296e-07]
 [-2.88875526e-07 -1.40416887e-07 -7.95716915e-09 -1.90051651e-07
  -4.43051249e-08 -1.83505108e-07 -3.27732778e-07]
 [-2.17540219e-07 -2.47640855e-07 -1.11256668e-07 -2.04696335e-07
  -3.58220859e-07 -2.21361915e-07  3.06372385e-08]
 [-2.36483174e-07 -1.97824193e-07 -4.43594217e-07  1.85998942e-07
   1.14585418e-07 -5.87579